### ISSUE TITLE
LockedDetail type shoud be []any or struct 

### ISSUE THREAD

**Issue by yrbb** [GoPlusSecurity/goplus-sdk-go#14]
LockedDetail type shoud be []any
file: https://github.com/GoPlusSecurity/goplus-sdk-go/blob/main/pkg/gen/models/response_wrapper_token_security.go#L580

https://gopluslabs.io/token-security/1/0xB22C05CeDbF879a661fcc566B5a759d005Cf7b4C

response:
`
"locked_detail":[
      {
          "amount":"30000000",
          "end_time":"2023-07-01T05:00:00+00:00",
          "opt_time":""
      },
      {
          "amount":"30000000",
          "end_time":"2023-08-01T05:00:00+00:00",
          "opt_time":""
      }
 ]
`

**Comment by Origin-zhao** [comment]
json: cannot unmarshal object into Go struct field ResponseWrapperTokenSecurityResultAnonLpHoldersItems0.result.lp_holders.locked_detail of type string"

**Comment by cong08** [comment]
> 

Thanks for reporting the issue, we just fixed it in our latest [release v1.2.0](https://github.com/GoPlusSecurity/goplus-sdk-go/releases/tag/v1.2.0) and I am closing the issue, feel free to reopen it if you see any issues.
