### ISSUE TITLE
cannot unmarshal number into Go struct field ResponseWrapperTokenSecurityResultAnonHoldersItems0.result.holders.percent of type string

### ISSUE THREAD

**Issue by rjjuina** [GoPlusSecurity/goplus-sdk-go#21]
```
var ret    models.ResponseWrapperTokenSecurityResultAnon
security = token.NewTokenSecurity(nil)
 ret, err := security.Run(chainId, []string{tokenAddr})
```

cannot unmarshal number into Go struct field ResponseWrapperTokenSecurityResultAnonHoldersItems0.result.holders.percent of type string

I guess that the tag `json:",string" should be used to 

```
         // It  describes the percentage of tokens held by this holder (Notice:About "percent": 1 means 100% here.)
	Percent string `json:"percent,string,omitempty"`
``` 
of ResponseWrapperTokenSecurityResultAnonHoldersItems0 struct,

**Comment by cong08** [comment]
> ```
> var ret    models.ResponseWrapperTokenSecurityResultAnon
> security = token.NewTokenSecurity(nil)
>  ret, err := security.Run(chainId, []string{tokenAddr})
> ```
> 
> cannot unmarshal number into Go struct field ResponseWrapperTokenSecurityResultAnonHoldersItems0.result.holders.percent of type string
> 
> I guess that the tag `json:",string" should be used to
> 
> ```
>          // It  describes the percentage of tokens held by this holder (Notice:About "percent": 1 means 100% here.)
> 	Percent string `json:"percent,string,omitempty"`
> ```
> 
> of ResponseWrapperTokenSecurityResultAnonHoldersItems0 struct,



> ```
> var ret    models.ResponseWrapperTokenSecurityResultAnon
> security = token.NewTokenSecurity(nil)
>  ret, err := security.Run(chainId, []string{tokenAddr})
> ```
> 
> cannot unmarshal number into Go struct field ResponseWrapperTokenSecurityResultAnonHoldersItems0.result.holders.percent of type string
> 
> I guess that the tag `json:",string" should be used to
> 
> ```
>          // It  describes the percentage of tokens held by this holder (Notice:About "percent": 1 means 100% here.)
> 	Percent string `json:"percent,string,omitempty"`
> ```
> 
> of ResponseWrapperTokenSecurityResultAnonHoldersItems0 struct,

Can you tell me your request parameters?

**Comment by cong08** [comment]
chainId and tokenAddr @rjjuina

**Comment by rjjuina** [comment]
chainId: 1
tokenAddr: 0x95146474d59798ac6d1550c9ef9471d09f430d21

**Comment by cong08** [comment]
Thank you! we just fixed it. you can try agin. @rjjuina
