### ISSUE TITLE
ResponseWrapperTokenSecurityResultAnonLpHoldersItems0.Balance field type has some error

### ISSUE THREAD

**Issue by fms5cmS** [GoPlusSecurity/goplus-sdk-go#29]
API: Get token's security and risk data
GET https://api.gopluslabs.io/api/v1/token_security/{chain_id}

desc: sometime the lp_holders.balance type in response not match sdk type

example:
params: `chain_id = 1` and `address=0x1c388bEef4178493F1EFC28962eEA02eE0DD6837`
in the response, `lp_holders[0].balance = 0`, whitch type is int, but `ResponseWrapperTokenSecurityResultAnonLpHoldersItems0.Balance` field type is string in this sdk,

<img width="796" alt="image" src="https://github.com/GoPlusSecurity/goplus-sdk-go/assets/36298380/82790304-1e69-441c-8393-a72c20044e16">

**Comment by fms5cmS** [comment]
NFTList.amount has same problem

**Comment by cong08** [comment]
we just fixed it. you can try agin.
